algoritmo "Exercício 28"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Gustavo Guanabara
// Autor(a)    : Pedro Luiz Melo Sobral
// Data atual  : 21/12/2022
var
   L, M, Area: real
Inicio
   Repita
      EscrevaL("Digite a largura e a altura")
      Leia(L, M)
   Ate
   
   Se Entao
   Senao
      Se Entao
      Senao
         Se Entao
         FimSe
      FimSe
   FimSe
fimalgoritmo

