algoritmo "Exercício 9"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Gustavo Guanabara
// Autor(a)    : Pedro Luiz Melo Sobral
// Data atual  : 16/12/2022
var
   Reais, Resp: real
Funcao conversor():real
Inicio
   retorne reais / 3.45
FimFuncao

Inicio
   EscrevaL("Digite o valor em reais: ")
   Leia(reais)
   Resp <- conversor()
   EscrevaL("Valor em dolares ", Resp)
fimalgoritmo

