 algoritmo "Creuzinha"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Gustavo Guanabara
// Descrição   : Creuzinha é muito burra! Precisamos ajuda-lá
//               Exercício 2: Converter real para dolar
// Autor(a)    : Pedro Luiz Melo Sobral
// Data atual  : 04/04/2023
var
   reais, dolar: real
inicio
   escreva("Quantos reais você tem? ")
   leia(reais)
   dolar <- reais/5.85
   escreva("Seu valor em dolar é: ",dolar:2:2)
fimalgoritmo