algoritmo "Operadores_relacionais"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Gustavo Guanabara
// Descrição   : Testar a interação em operadores relacionais
// Autor(a)    : Pedro Luiz Melo Sobral
// Data atual  : 04/04/2023
var
   a, b, c: inteiro
inicio
   a <- 2
   b <- 3
   c <- 5
   // O resultado da intereção entre dois operadores relacionais sempre vai
   // ser um valor lógico
   escreva (a > b)
   escreva (a = b)
   escreva (a <> b)
fimalgoritmo