Algoritmo "Conta Ate 10 procedimento"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Gustavo Guanabara
// Descrição   : Contar até 10 usando estrutura de Repetição Enquanto Usando procedimento
// Autor(a)    : Pedro Luiz Melo Sobral
// Data atual  : 13/12/2022
Var
   Cont: inteiro
   
Procedimento Contar()
Inicio
      Cont <- 0
   Enquanto (Cont <= 10) Faca
      EscrevaL(Cont)
      Cont <- Cont + 1
   FimEnquanto
FimProcedimento

Inicio
   Contar()
Fimalgoritmo