Algoritmo "Conta Ate 10"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Gustavo Guanabara
// Descrição   : Contar até 10 usando estrutura de Repetição Enquanto
// Autor(a)    : Pedro Luiz Melo Sobral
// Data atual  : 26/11/2022
// Observação:
Var
   Cont: inteiro
Inicio
   Cont <- 0
   Enquanto (Cont <= 10) Faca
      EscrevaL(Cont)
      Cont <- Cont + 1
   FimEnquanto
Fimalgoritmo