Algoritmo "Conta Ate 0 procedimento"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Gustavo Guanabara
// Descrição   : contar até 0 com estrutura de repetição enquanto usando procedimentos
// Autor(a)    : Pedro Luiz Melo Sobral
// Data atual  : 26/11/2022
Var
   Cont: inteiro

Procedimento Contar()
Inicio
   Cont <- 10
   Enquanto (Cont >= 0) Faca
      EscrevaL(Cont)
      Cont <- Cont - 1
   FimEnquanto
FimProcedimento

Inicio

   Contar()
Fimalgoritmo