Algoritmo "Comando Leia Procedimentos"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Gustavo Guanabara
// Descrição   : Utilizar procedimentos para dar Comandos de entrada
// Autor(a)    : Pedro Luiz Melo Sobral
// Data atual  : 11/12/2022
Var
Procedimento ComandoEntrada()
Var
   nome: caractere
Inicio
   Escreva("Qual é o seu nome?")
   Leia(nome)
   Escreval("Muito prazer!",nome)
FimProcedimento
Inicio
   ComandoEntrada()
Fimalgoritmo