algoritmo "Contador 1 a 10 Procedimento"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Gustavo Guanabara
// Descrição   :  Fazer uma contagem de 1 ate 10 usando estrutura de repetição
//                repita usando procedimentos
// Autor(a)    : Pedro Luiz Melo Sobral
// Data atual  : 14/12/2022
var
   Cont: inteiro
Procedimento Contador()
inicio
   Repita
      EscrevaL(Cont)
      Cont <- Cont + 1
   Ate (Cont > 10)
FimProcedimento
Inicio
   Contador()
fimalgoritmo
