algoritmo "Contador 1 a 10"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Gustavo Guanabara
// Descrição   :  Fazer uma contagem de 1 ate 10 usando estrutura de repetição
//                repita
// Autor(a)    : Pedro Luiz Melo Sobral
// Data atual  : 29/11/2022
var
   Cont: inteiro
inicio
   Repita
      EscrevaL(Cont)
      Cont <- Cont + 1
   Ate (Cont > 10)
fimalgoritmo
