algoritmo "Contagem Para procedimento"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Gustavo Guanabara
// Descrição   : Fazer uma contagem simples usando estrutra de repetição para usando procedimentos
// Autor(a)    : Pedro Luiz Melo Sobral
// Data atual  : 14/12/2022
var
   Cont: inteiro
Procedimento Contador()
inicio
   para Cont <- 1 ate 10 passo 1 faca
      EscrevaL(Cont)
   FimPara
FimProcedimento

Inicio
   Contador()
fimalgoritmo
