Algoritmo "Comparação Procedimento"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Gustavo Guanabara
// Descrição   : Realizar uma comparação por meio de procedimentos
// Autor(a)    : Pedro Luiz Melo Sobral
// Data atual  : 11/12/2022
Var a, b: inteiro
Procedimento Comparador(x, y: inteiro)
Inicio
   EscrevaL(a > b)
FimProcedimento
Inicio
   EscrevaL("Valor Maior: ")
   Leia(a)
   EscrevaL("Valor Menor: ")
   Leia(b)
   Comparador(a, b)
Fimalgoritmo