algoritmo "Soma Função"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Gustavo Guanabara
// Descrição   : Testando soma na com funções
// Autor(a)    : Pedro Luiz Melo Sobral
// Data atual  : 08/12/2022
// Observação:
var
  v1, v2, s: inteiro
Funcao soma(x, y: inteiro):inteiro
  Retorne x + y
FimFuncao
inicio
   EscrevaL("Digite o primeiro valor: ")
   Leia(v1)
   EscrevaL("Digite o primeiro valor: ")
   Leia(v2)
   s <- soma(v1, v2)
   EscrevaL(s)
fimalgoritmo

