Algoritmo "Comparação De Operadores Logicos"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Gustavo Guanabara
// Descrição   : Comparar resultados de operadores relacionais
//               Por meio de comparações lógicas
// Autor(a)    : Pedro Luiz Melo Sobral
// Data atual  : 20/09/2022
Var
   a, b, c: Inteiro
Inicio
      a <- 1
      b <- 2
      c <- 3
      Escreval((a>b) e (c>a))
      Escreval((b>a) ou (c>a))
      Escreval(não(a>b))
Fimalgoritmo