Algoritmo "Impar Ou Par"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Gustavo Guanabara
// Descrição   : Verificar se um número é impar ou par
// Autor(a)    : Pedro Luiz Melo Sobral
// Data atual  : 24/11/2022
Var
   numero: inteiro
Inicio
   Escreva("Digite algum número: ")
   Leia(numero)
   Se (numero%2 = 0)   Entao
      EscrevaL("Seu número é Par")
   Senao
      EscrevaL("Seu número é Impar")
   FimSe
Fimalgoritmo