Algoritmo "ExercicioContagemRegressiva"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : gustavo guanabara
// Descrição   : Desenvolver uma contagem regressiva
// Autor(a)    : Pedro Luiz Melo Sobral
// Data atual  : 09/06/2022
Var
   contador: inteiro
Inicio
   contador <- 5
   enquanto contador >= 0 faca
      escreval(contador)
      contador <- contador - 1
   fimenquanto
Fimalgoritmo