Algoritmo "ExercicioCombinações"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : gustavo guanabara
// Descrição   : Mostrar as matrizes de 3 valores na tela
// Autor(a)    : Pedro Luiz Melo Sobral
// Data atual  : 27/07/2022
Var
   c1, c2, c3: inteiro
Inicio
   para c1 <- 1 ate 3 faca
      para c2 <- 1 ate 3 faca
         para c3 <- 1 ate 3 faca
            escreval(c1, c2, c3)
         fimpara
      fimpara
   fimpara
Fimalgoritmo